services:
  - type: web
    name: rcvb-v1-platform
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /healthz
    autoDeployTrigger: commit
